[tool.poetry]
name = "rct-power"
version = "0.10.0"
description = ""
authors = ["Felix Stürmer <stuermer@weltenwort.de>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.10"

[tool.poetry.dev-dependencies]
async_timeout = "^4.0.0"
black = "^23.3.0"
flake8 = "^6.0.0"
homeassistant = "^2023.5.4"
pre-commit = "^3.2.2"
rctclient = "^0.0.3"
reorder-python-imports = "^3.9.0"
pytest-homeassistant-custom-component = "^0.13.32"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.pyright]
typeCheckingMode = "strict"
reportMissingTypeStubs = "warning"
reportImportCycles = "warning"
useLibraryCodeForTypes = true
